# ЛР 1. Введение. Инструменты python для базовых задач МО.

# Теория

## Подключаю библиотеки

In [1]:
import numpy as np

In [2]:
np.__version__

'1.25.2'

## Математические функции для операций с массивами.

In [3]:
np.arctan(1)

0.7853981633974483

In [4]:
np.pi / 4

0.7853981633974483

## Создаю массивы

In [5]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [6]:
a = np.array([1, 2, 3, 4], dtype = 'float32')
a

array([1., 2., 3., 4.], dtype=float32)

Добавление в конец массива

In [7]:
np.append(a, 2)

array([1., 2., 3., 4., 2.])

<font color="red"> Важно не забывать присваивать исходному массиву результат работы метода, если массив хочется изменить.<font>

In [8]:
a

array([1., 2., 3., 4.], dtype=float32)

In [9]:
np.array([range(i, i + 3) for i in [2, 4, 6]]) #преобразование вложенных данных в массив

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

Вспоминаю, как работает range.

In [10]:
for i in range(4, 10):
    print(i)

4
5
6
7
8
9


Ну и свой пример.

In [11]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Массив из нулей.

In [12]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

По умолчанию не целочисленный тип.

In [13]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.zeros((3, 3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

Массив из единиц.

In [15]:
np.ones((3, 3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

Заполняю массив.

In [16]:
np.full((3, 3), np.pi)

array([[3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265]])

Разница между arange и linspace. arange создает массив с использованием шага, который я указываю, при этом количество эдементов я не могу проконтролировать и указываемый мной верхний диапазон никогда не будет включен в массив. linspace же включает оба промежутка с заданным мной количеством элементов.

In [17]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [18]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

Возвращает последовательность данных, равномерно расположенных в заданном интервале на числовой прямой в логарифмическом масштабе.

In [19]:
np.logspace(0, 1, 5) # последовательность степеней

array([ 1.        ,  1.77827941,  3.16227766,  5.62341325, 10.        ])

In [20]:
10 ** np.linspace(0, 3, 4)

array([   1.,   10.,  100., 1000.])

In [21]:
np.logspace(0, 5, 6, base = 2)

array([ 1.,  2.,  4.,  8., 16., 32.])

Массивы случайных чисел.

In [22]:
np.random.random((3, 3))

array([[0.72557834, 0.7498125 , 0.11214657],
       [0.84915884, 0.6371339 , 0.43614308],
       [0.62258998, 0.35471018, 0.24763155]])

In [23]:
np.random.randint(0, 10, (3, 3))

array([[6, 5, 8],
       [7, 5, 7],
       [5, 1, 9]])

Единичная матрица

In [24]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
test = np.array([[1, 2], [3, 4]], dtype = 'int32')
test

array([[1, 2],
       [3, 4]])

In [26]:
test[0] = [3.14, 2.0001]

Произошло округление.

In [27]:
test

array([[3, 2],
       [3, 4]])

In [28]:
test = np.append(test, [3.14, 2.0001])

Выровнялся массив и поменялся тип.

In [29]:
test

array([3.    , 2.    , 3.    , 4.    , 3.14  , 2.0001])

In [30]:
test.dtype

dtype('float64')

Количество байт, потребляемое элементами массива.

In [31]:
test.nbytes

48

In [32]:
np.fromfunction(lambda i, j: i + j, (3, 3), dtype = int) #элементы зависят от индекса

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

Возвращает массив, состоящий из нулей той же формы и типа, что и данный массив.

In [33]:
np.zeros_like(test)

array([0., 0., 0., 0., 0., 0.])

## Доступ к элементам массива

Создаю массивы.

In [34]:
x1 = np.random.randint(10, size=6)  
x2 = np.random.randint(10, size=(3, 4))  
x3 = np.random.randint(10, size=(3, 4, 5))  

In [35]:
x1

array([3, 6, 7, 3, 5, 8])

In [36]:
x2

array([[0, 0, 3, 8],
       [6, 3, 3, 3],
       [4, 7, 8, 4]])

In [37]:
x3

array([[[7, 9, 2, 6, 9],
        [9, 0, 6, 5, 5],
        [5, 5, 7, 1, 0],
        [9, 3, 6, 6, 2]],

       [[8, 7, 1, 6, 2],
        [0, 6, 9, 3, 7],
        [2, 6, 0, 5, 7],
        [2, 4, 7, 7, 8]],

       [[6, 5, 5, 1, 0],
        [4, 3, 3, 7, 4],
        [9, 0, 4, 7, 8],
        [6, 4, 6, 8, 6]]])

Практикую доступ к элементам.

In [38]:
x1[0]

3

In [39]:
x1[-1]

8

In [40]:
x2

array([[0, 0, 3, 8],
       [6, 3, 3, 3],
       [4, 7, 8, 4]])

In [41]:
x2[0,1]

0

In [42]:
x2[0,-1]

8

In [43]:
x1

array([3, 6, 7, 3, 5, 8])

Конец, указанный в срезе, не учитывается по шагу. Возвращается массив.

In [44]:
# x[start:stop:step]
x1[1:-1:2]

array([6, 3])

In [45]:
x1[:5]

array([3, 6, 7, 3, 5])

In [46]:
x1[::2]

array([3, 7, 5])

In [47]:
x1[::-1] # разворот

array([8, 5, 3, 7, 6, 3])

In [48]:
x2

array([[0, 0, 3, 8],
       [6, 3, 3, 3],
       [4, 7, 8, 4]])

Сначала строчки, потом столбцы через запятую.

In [49]:
x2[:2,:2]

array([[0, 0],
       [6, 3]])

In [50]:
x2[:,::-1]

array([[8, 3, 0, 0],
       [3, 3, 3, 6],
       [4, 8, 7, 4]])

Вот так можно указывать столбцы.

In [51]:
x2[:,[3,2,1]]

array([[8, 3, 0],
       [3, 3, 3],
       [4, 8, 7]])

Просто весь второй столбец.

In [52]:
x2[:,2] #столбец

array([3, 3, 8])

In [53]:
x2[2,:] #строка

array([4, 7, 8, 4])

In [54]:
x2_child = x2[2,:] # подмассив

In [55]:
x2_child[0] = 2023

А вот так работают массивы, так как обе переменные будут ссылаться на один объект в памяти, изменение одной из них будет видно и в других.

In [56]:
x2_child

array([2023,    7,    8,    4])

In [57]:
x2

array([[   0,    0,    3,    8],
       [   6,    3,    3,    3],
       [2023,    7,    8,    4]])

In [58]:
x2_grownup_child = x2[0,:].copy() # копия для разрыва связи с базовым массивом

In [59]:
x2_grownup_child

array([0, 0, 3, 8])

In [60]:
x2_grownup_child[0] = 2023

In [61]:
x2_grownup_child

array([2023,    0,    3,    8])

In [62]:
x2

array([[   0,    0,    3,    8],
       [   6,    3,    3,    3],
       [2023,    7,    8,    4]])

## Изменение структуры массива

In [63]:
grid = np.arange(1, 10)
grid

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
grid = grid.reshape(3, 3) #создаём массив потом меняем его форму
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [65]:
np.arange(1, 10).reshape(3, 2)

ValueError: cannot reshape array of size 9 into shape (3,2)

In [66]:
x = np.array([1, 2, 3])
x.reshape((1, 3)) 

array([[1, 2, 3]])

In [67]:
x.reshape(3, 1) 

array([[1],
       [2],
       [3]])

Увеличиваю размерность массива.

In [68]:
x[np.newaxis,:]

array([[1, 2, 3]])

In [69]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [70]:
z = np.array([99, 99, 99])
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [71]:
grid1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

Буду склеивать элементы массивов на первом уровне вложенности.

In [72]:
grid2 = np.zeros((2,3))
grid2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [73]:
np.concatenate([grid1, grid2]) # конкатенация по 1 - ому измерению

array([[1., 2., 3.],
       [4., 5., 6.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [74]:
np.concatenate([grid1, grid2],axis = 1) # конкатенация по 2 - ому измерению

array([[1., 2., 3., 0., 0., 0.],
       [4., 5., 6., 0., 0., 0.]])

Присоединяю данные по вертикальной и горизонтальной осям.

In [75]:
np.vstack([grid1, grid2])

array([[1., 2., 3.],
       [4., 5., 6.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [76]:
np.hstack([grid1, grid2])

array([[1., 2., 3., 0., 0., 0.],
       [4., 5., 6., 0., 0., 0.]])

In [77]:
x = np.array([1, 2, 3, 99, 99, 3, 2, 1])
np.split(x, 4) # разделение массива

[array([1, 2]), array([ 3, 99]), array([99,  3]), array([2, 1])]

Разделит массив по указанным индексам.

In [78]:
np.split(x,[3, 5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [79]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [80]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [81]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


## Векторизация

In [82]:
big_array = np.random.randint(1,100,1000000)

In [83]:
1/big_array

array([0.02439024, 0.02      , 0.01030928, ..., 0.01020408, 0.03703704,
       0.01818182])

In [84]:
%timeit 1/big_array

4.94 ms ± 269 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


Поэлементное выполнение операций.

In [88]:
np.arange(5) / np.arange(1, 6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [89]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [90]:
np.arange(1, 6)

array([1, 2, 3, 4, 5])

In [91]:
2*np.arange(5) 

array([0, 2, 4, 6, 8])

То же самое и с возведением в степень.

In [93]:
x = np.arange(9).reshape((3, 3))
2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]], dtype=int32)

In [94]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [96]:
x**x

array([[       1,        1,        4],
       [      27,      256,     3125],
       [   46656,   823543, 16777216]])

In [97]:
x = np.arange(4)
print("x      =", x)
print("x + 5  =", x + 5)
print("x - 5  =", x - 5)
print("x * 2  =", x * 2)
print("x / 2  =", x / 2)
print("x // 2 =", x // 2)
print("-x     = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2  = ", x % 2)

x      = [0 1 2 3]
x + 5  = [5 6 7 8]
x - 5  = [-5 -4 -3 -2]
x * 2  = [0 2 4 6]
x / 2  = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]
-x     =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2  =  [0 1 0 1]


In [98]:
x = [1, 2, 4, 10]
print("x        =", x)
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x)) # куча математических функций и все с векторизацией

x        = [1, 2, 4, 10]
ln(x)    = [0.         0.69314718 1.38629436 2.30258509]
log2(x)  = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


In [99]:
x = np.arange(1, 6)
np.add.reduce(x)

15

In [100]:
np.multiply.reduce(x)

120

In [101]:
x = np.arange(1, 6)
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15])

In [102]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120])

In [109]:
big_array = np.random.random(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

118 ms ± 1.28 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
1.38 ms ± 8.83 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [110]:
np.min(big_array), np.max(big_array)

(4.792749607185343e-07, 0.9999991397595301)

In [112]:
test= np.random.randint(100,size=(10,10))
test

array([[21, 85, 31, 73, 94, 18, 64, 20, 38, 11],
       [43, 67, 85, 27, 75, 59, 94, 72, 63, 14],
       [24, 35,  4, 83, 90, 90, 25, 26, 29, 71],
       [69, 43, 51, 57, 50, 86, 43, 67, 84, 87],
       [56, 53, 19, 38, 20, 83, 91, 65, 19,  0],
       [73, 42, 51, 82, 32, 13, 89, 10, 98, 62],
       [73, 63, 55, 83, 14, 86, 69, 15, 69, 30],
       [13, 40, 53,  7, 52, 24, 53, 43,  4, 12],
       [82, 21, 12, 49,  5, 98, 62, 29, 59, 74],
       [48, 54,  4, 19, 16, 14, 50, 48, 17, 52]])

In [113]:
test.min(axis=0) # минимум по столбцам

array([13, 21,  4,  7,  5, 13, 25, 10,  4,  0])

## Операции

In [243]:
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
a + b



array([5, 6, 7])

In [244]:
M = np.ones((3, 3))
M

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [245]:
a

array([0, 1, 2])

In [246]:
M + a # numpy array broadcasting

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

Увеличиваю размерность.

In [118]:
a = np.arange(3)
b = np.arange(3)[:, np.newaxis]

print(a)
print(b)

[0 1 2]
[[0]
 [1]
 [2]]


In [119]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [126]:
np.repeat([a],3,axis=0)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [129]:
np.repeat(b,3,axis=1)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]])

In [131]:
(np.repeat(b,3,axis=1) + np.repeat([a],3,axis=0), a + b)

(array([[0, 1, 2],
        [1, 2, 3],
        [2, 3, 4]]),
 array([[0, 1, 2],
        [1, 2, 3],
        [2, 3, 4]]))

In [132]:
M = np.ones((3, 2))
a = np.arange(3)

In [133]:
a

array([0, 1, 2])

In [135]:
M

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [137]:
M + a

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

In [138]:
a = np.array([4,5,6,7])  
b = np.array([1,3,5,7,9,11,14,10])  
c = a+b;  

ValueError: operands could not be broadcast together with shapes (4,) (8,) 

In [139]:
matrix1 = np.array([[1, 3], [5, 7]])
             
matrix2 = np.array([[2, 6], [4, 8]])

result = np.dot(matrix1, matrix2)

print("matrix1 x matrix2: \n",result)

matrix1 x matrix2: 
 [[14 30]
 [38 86]]


In [140]:
matrix1 = np.random.randint(10,size=(3,2))
matrix1

array([[7, 8],
       [9, 1],
       [9, 1]])

In [141]:
matrix2 = np.random.randint(10,size=(2,3))
matrix2

array([[5, 8, 1],
       [9, 0, 3]])

In [142]:
np.dot(matrix1,matrix2)

array([[107,  56,  31],
       [ 54,  72,  12],
       [ 54,  72,  12]])

In [143]:
np.dot(matrix2,matrix1)

array([[116,  49],
       [ 90,  75]])

In [144]:
np.dot(matrix1,matrix1)

ValueError: shapes (3,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [145]:
matrix1=np.array([1,2,3])

In [146]:
matrix2 = np.random.randint(10,size=(3,3))

In [147]:
np.dot(matrix2,matrix1)

array([22, 14, 29])

In [149]:
matrix1

array([1, 2, 3])

In [150]:
matrix2

array([[3, 8, 1],
       [1, 2, 3],
       [8, 3, 5]])

In [152]:
np.matmul(matrix2,matrix1)

array([22, 14, 29])

In [153]:
matrix1

array([1, 2, 3])

In [155]:
np.multiply(matrix1,matrix1)

array([1, 4, 9])

In [156]:
matrix1 = np.array([[1, 3], [5, 7]])

In [157]:
matrix1 - matrix1 

array([[0, 0],
       [0, 0]])

In [158]:
matrix1 = matrix1 + matrix1
matrix1

array([[ 2,  6],
       [10, 14]])

In [159]:
np.add(matrix1,matrix1,out=matrix1)
matrix1

array([[ 4, 12],
       [20, 28]])

In [160]:
matrix1.T

array([[ 4, 20],
       [12, 28]])

In [161]:
np.linalg.det(matrix1)

-127.99999999999997

In [162]:
np.linalg.inv(matrix1)

array([[-0.21875,  0.09375],
       [ 0.15625, -0.03125]])

In [163]:
np.dot(matrix1, np.linalg.inv(matrix1)).astype(int)

array([[1, 0],
       [0, 1]])

## Булевы операции

In [164]:
x

array([1, 2, 3, 4, 5])

In [165]:
x>2

array([False, False,  True,  True,  True])

In [166]:
x[x>2]=0

In [167]:
x

array([1, 2, 0, 0, 0])

In [168]:
np.any(x==0)

True

In [169]:
np.all(x==0)

False

Посчитает, там, где True.

In [173]:
np.sum(x>1)

1

In [174]:
np.sum(x[x>1])

2

In [175]:
matrix1

array([[ 4, 12],
       [20, 28]])

In [176]:
np.where(matrix1 == 3)

(array([], dtype=int64), array([], dtype=int64))

In [177]:
Z = np.random.randint(1,10, 10)
print(Z)

Z[Z.argmax()] = 0
print(Z)

[2 6 8 8 2 8 2 8 8 6]
[2 6 0 8 2 8 2 8 8 6]


In [178]:
Z.argmin()

2

# Задания

## 1.

### 2. Реализуйте функцию для создания "шахматной" квадратной двоичной матрицы произвольного размера.

In [87]:
def get_chess_form(n):
    chess_template_1 = np.zeros(n, dtype=int)
    chess_template_2 = np.zeros(n, dtype=int)
    chess_template_1[1::2] = 1
    chess_template_2[::2] = 1
    chess_template_3 = np.vstack([chess_template_1, chess_template_2])
    res = np.vstack([chess_template_3] * int (n / 2))
    if (n % 2):
        res = np.vstack([res, chess_template_1])
    return res

In [88]:
N = 8
chess_arr = get_chess_form(N)
chess_arr

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

### 3. Реализуйте функцию для создания матрицы для сетки координа x и y, покрывающими область [0,1] x [0,1] на плоскости. На вход функция принимает количество точек сетки.

Первый способ решения.

In [299]:
def get_grid_digits(n):
    t = np.linspace(0, 1, n)
    t_grid = np.vstack([t] * n)
    # t_grid[:,:1] = t_grid[:,:1] + np.reshape(t[::-1], (n, 1))
    return t_grid

In [300]:
get_grid_digits(6)

array([[0. , 0.2, 0.4, 0.6, 0.8, 1. ],
       [0. , 0.2, 0.4, 0.6, 0.8, 1. ],
       [0. , 0.2, 0.4, 0.6, 0.8, 1. ],
       [0. , 0.2, 0.4, 0.6, 0.8, 1. ],
       [0. , 0.2, 0.4, 0.6, 0.8, 1. ],
       [0. , 0.2, 0.4, 0.6, 0.8, 1. ]])

Второй способ решения.

In [301]:
def get_grid_lists(n):
    test = np.zeros((n, n, 2))
    t = np.linspace(0, 1, n)
    test[:, :, 1:] = np.reshape(t[::-1], (n, 1, 1))
    test[:, :, :1] = np.reshape(t, (n, 1))
    return test

In [302]:
show_arr(get_grid_lists(6))

[0. 1.] [0.2 1. ] [0.4 1. ] [0.6 1. ] [0.8 1. ] [1. 1.] 
[0.  0.8] [0.2 0.8] [0.4 0.8] [0.6 0.8] [0.8 0.8] [1.  0.8] 
[0.  0.6] [0.2 0.6] [0.4 0.6] [0.6 0.6] [0.8 0.6] [1.  0.6] 
[0.  0.4] [0.2 0.4] [0.4 0.4] [0.6 0.4] [0.8 0.4] [1.  0.4] 
[0.  0.2] [0.2 0.2] [0.4 0.2] [0.6 0.2] [0.8 0.2] [1.  0.2] 
[0. 0.] [0.2 0. ] [0.4 0. ] [0.6 0. ] [0.8 0. ] [1. 0.] 


Как я разбирался со вторым способом.

In [303]:
N = 5
test = np.zeros((N, N, 2))

In [304]:
def show_arr(arr):
    for i in arr:
        for j in range(len(i)):
            print(i[j], end=' ')
        print()

In [305]:
show_arr(test)

[0. 0.] [0. 0.] [0. 0.] [0. 0.] [0. 0.] 
[0. 0.] [0. 0.] [0. 0.] [0. 0.] [0. 0.] 
[0. 0.] [0. 0.] [0. 0.] [0. 0.] [0. 0.] 
[0. 0.] [0. 0.] [0. 0.] [0. 0.] [0. 0.] 
[0. 0.] [0. 0.] [0. 0.] [0. 0.] [0. 0.] 


In [306]:
t = np.linspace(0, 1, N)

In [307]:
t

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [308]:
test

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [309]:
show_arr(test)

[0. 0.] [0. 0.] [0. 0.] [0. 0.] [0. 0.] 
[0. 0.] [0. 0.] [0. 0.] [0. 0.] [0. 0.] 
[0. 0.] [0. 0.] [0. 0.] [0. 0.] [0. 0.] 
[0. 0.] [0. 0.] [0. 0.] [0. 0.] [0. 0.] 
[0. 0.] [0. 0.] [0. 0.] [0. 0.] [0. 0.] 


In [310]:
test[:, :, :1]

array([[[0.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.]]])

In [311]:
t

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [312]:
test[:, :, 1:] = np.reshape(t[::-1], (N, 1, 1))

In [313]:
show_arr(test)

[0. 1.] [0. 1.] [0. 1.] [0. 1.] [0. 1.] 
[0.   0.75] [0.   0.75] [0.   0.75] [0.   0.75] [0.   0.75] 
[0.  0.5] [0.  0.5] [0.  0.5] [0.  0.5] [0.  0.5] 
[0.   0.25] [0.   0.25] [0.   0.25] [0.   0.25] [0.   0.25] 
[0. 0.] [0. 0.] [0. 0.] [0. 0.] [0. 0.] 


In [314]:
test[:, :, :1] = np.reshape(t, (N, 1))

In [315]:
show_arr(test)

[0. 1.] [0.25 1.  ] [0.5 1. ] [0.75 1.  ] [1. 1.] 
[0.   0.75] [0.25 0.75] [0.5  0.75] [0.75 0.75] [1.   0.75] 
[0.  0.5] [0.25 0.5 ] [0.5 0.5] [0.75 0.5 ] [1.  0.5] 
[0.   0.25] [0.25 0.25] [0.5  0.25] [0.75 0.25] [1.   0.25] 
[0. 0.] [0.25 0.  ] [0.5 0. ] [0.75 0.  ] [1. 0.] 


In [316]:
np.reshape(t, (N, 1))

array([[0.  ],
       [0.25],
       [0.5 ],
       [0.75],
       [1.  ]])

In [317]:
test[:, :, :1]

array([[[0.  ],
        [0.25],
        [0.5 ],
        [0.75],
        [1.  ]],

       [[0.  ],
        [0.25],
        [0.5 ],
        [0.75],
        [1.  ]],

       [[0.  ],
        [0.25],
        [0.5 ],
        [0.75],
        [1.  ]],

       [[0.  ],
        [0.25],
        [0.5 ],
        [0.75],
        [1.  ]],

       [[0.  ],
        [0.25],
        [0.5 ],
        [0.75],
        [1.  ]]])

## 2

### 1. Реализуйте учебную модель Игры "Жизнь". Создайте также динамическое изображение.

Ход работы.

In [391]:
N = 5
field = np.random.randint(2, size=(N, N))
field

array([[1, 1, 0, 1, 0],
       [1, 1, 1, 0, 0],
       [1, 0, 1, 1, 1],
       [1, 1, 0, 0, 0],
       [1, 0, 1, 0, 0]])

In [392]:
horizontal_buff = np.zeros(N, dtype=int)
horizontal_buff

array([0, 0, 0, 0, 0])

In [393]:
vertical_buff = np.zeros(N, dtype=int)
vertical_buff = np.reshape(vertical_buff, (N, 1))
vertical_buff

array([[0],
       [0],
       [0],
       [0],
       [0]])

In [394]:
np.vstack([horizontal_buff, field[:N - 1, :]])

array([[0, 0, 0, 0, 0],
       [1, 1, 0, 1, 0],
       [1, 1, 1, 0, 0],
       [1, 0, 1, 1, 1],
       [1, 1, 0, 0, 0]])

In [395]:
np.vstack([field[1:, :], horizontal_buff])

array([[1, 1, 1, 0, 0],
       [1, 0, 1, 1, 1],
       [1, 1, 0, 0, 0],
       [1, 0, 1, 0, 0],
       [0, 0, 0, 0, 0]])

In [396]:
np.hstack([field[:, 1:], vertical_buff])

array([[1, 0, 1, 0, 0],
       [1, 1, 0, 0, 0],
       [0, 1, 1, 1, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0]])

In [397]:
np.hstack([vertical_buff, field[:, :N - 1]])

array([[0, 1, 1, 0, 1],
       [0, 1, 1, 1, 0],
       [0, 1, 0, 1, 1],
       [0, 1, 1, 0, 0],
       [0, 1, 0, 1, 0]])

In [398]:
np.pad(field[:N - 1, :N - 1], (1, 0))  

array([[0, 0, 0, 0, 0],
       [0, 1, 1, 0, 1],
       [0, 1, 1, 1, 0],
       [0, 1, 0, 1, 1],
       [0, 1, 1, 0, 0]])

In [399]:
np.pad(field[1:, 1:], (0, 1))  

array([[1, 1, 0, 0, 0],
       [0, 1, 1, 1, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [400]:
np.pad(field[1:, :N - 1],((0, 1), (1, 0)))

array([[0, 1, 1, 1, 0],
       [0, 1, 0, 1, 1],
       [0, 1, 1, 0, 0],
       [0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0]])

In [401]:
np.pad(field[:N - 1, 1:],((1, 0), (0, 1)))

array([[0, 0, 0, 0, 0],
       [1, 0, 1, 0, 0],
       [1, 1, 0, 0, 0],
       [0, 1, 1, 1, 0],
       [1, 0, 0, 0, 0]])

In [402]:
field_copy = np.copy(field)
field_copy = field + np.vstack([horizontal_buff, field[:N - 1, :]]) + np.vstack([field[1:, :], horizontal_buff]) + np.hstack([field[:, 1:], vertical_buff]) + np.hstack([vertical_buff, field[:, :N - 1]]) + np.pad(field[:N - 1, :N - 1], (1, 0)) + np.pad(field[1:, 1:], (0, 1)) + np.pad(field[1:, :N - 1],((0, 1), (1, 0))) + np.pad(field[:N - 1, 1:],((1, 0), (0, 1)))

In [403]:
field_copy[field == 1] = field_copy[field == 1] - 1

In [404]:
field_copy

array([[3, 4, 4, 1, 1],
       [4, 6, 5, 5, 3],
       [4, 7, 4, 3, 1],
       [3, 5, 4, 4, 2],
       [2, 4, 1, 1, 0]])

In [405]:
field

array([[1, 1, 0, 1, 0],
       [1, 1, 1, 0, 0],
       [1, 0, 1, 1, 1],
       [1, 1, 0, 0, 0],
       [1, 0, 1, 0, 0]])

In [406]:
field[field_copy > 3] = 0

In [408]:
field[field_copy < 2] = 0

In [410]:
field[field_copy == 3] = 1

In [412]:
field[field_copy == 2] = 1

In [413]:
field

array([[1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 0]])

In [414]:
def life_game(n, times):
    field = np.random.randint(2, size=(n, n))
    horizontal_buff = np.zeros(n, dtype=int)
    vertical_buff = np.zeros(N, dtype=int)
    vertical_buff = np.reshape(vertical_buff, (N, 1))
    for i in times:
        field_copy = np.copy(field)
        field_copy = field + np.vstack([horizontal_buff, field[:N - 1, :]]) + np.vstack([field[1:, :], horizontal_buff]) + np.hstack([field[:, 1:], vertical_buff]) + np.hstack([vertical_buff, field[:, :N - 1]]) + np.pad(field[:N - 1, :N - 1], (1, 0)) + np.pad(field[1:, 1:], (0, 1)) + np.pad(field[1:, :N - 1],((0, 1), (1, 0))) + np.pad(field[:N - 1, 1:],((1, 0), (0, 1)))
        field_copy[field == 1] = field_copy[field == 1] - 1
        field[field_copy > 3] = 0
        field[field_copy < 2] = 0
        field[field_copy == 3] = 1
        field[field_copy == 2] = 1