# <font color = 'red'> ЛР 1. Введение. Инструменты python для базовых задач МО. </font>

# Теория

## Подключаю библиотеки

In [1]:
import numpy as np

In [2]:
np.__version__

'1.25.2'

## Математические функции для операций с массивами.

In [3]:
np.arctan(1)

0.7853981633974483

In [4]:
np.pi / 4

0.7853981633974483

## Создаю массивы

In [5]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [6]:
a = np.array([1, 2, 3, 4], dtype = 'float32')
a

array([1., 2., 3., 4.], dtype=float32)

Добавление в конец массива

In [7]:
np.append(a, 2)

array([1., 2., 3., 4., 2.])

<font color="red"> Важно не забывать присваивать исходному массиву результат работы метода, если массив хочется изменить.<font>

In [8]:
a

array([1., 2., 3., 4.], dtype=float32)

In [9]:
np.array([range(i, i + 3) for i in [2, 4, 6]]) #преобразование вложенных данных в массив

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

Вспоминаю, как работает range.

In [10]:
for i in range(4, 10):
    print(i)

4
5
6
7
8
9


Ну и свой пример.

In [11]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Массив из нулей.

In [12]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

По умолчанию не целочисленный тип.

In [13]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.zeros((3, 3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

Массив из единиц.

In [15]:
np.ones((3, 3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

Заполняю массив.

In [16]:
np.full((3, 3), np.pi)

array([[3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265]])

Разница между arange и linspace. arange создает массив с использованием шага, который я указываю, при этом количество эдементов я не могу проконтролировать и указываемый мной верхний диапазон никогда не будет включен в массив. linspace же включает оба промежутка с заданным мной количеством элементов.

In [17]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [18]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

Возвращает последовательность данных, равномерно расположенных в заданном интервале на числовой прямой в логарифмическом масштабе.

In [19]:
np.logspace(0, 1, 5) # последовательность степеней

array([ 1.        ,  1.77827941,  3.16227766,  5.62341325, 10.        ])

In [20]:
10 ** np.linspace(0, 3, 4)

array([   1.,   10.,  100., 1000.])

In [21]:
np.logspace(0, 5, 6, base = 2)

array([ 1.,  2.,  4.,  8., 16., 32.])

Массивы случайных чисел.

In [22]:
np.random.random((3, 3))

array([[0.80846603, 0.96409964, 0.5235869 ],
       [0.66240527, 0.15672281, 0.07530202],
       [0.96313747, 0.05561883, 0.04549746]])

In [23]:
np.random.randint(0, 10, (3, 3))

array([[0, 8, 1],
       [8, 8, 5],
       [3, 3, 8]])

Единичная матрица

In [24]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
test = np.array([[1, 2], [3, 4]], dtype = 'int32')
test

array([[1, 2],
       [3, 4]])

In [26]:
test[0] = [3.14, 2.0001]

Произошло округление.

In [27]:
test

array([[3, 2],
       [3, 4]])

In [28]:
test = np.append(test, [3.14, 2.0001])

Выровнялся массив и поменялся тип.

In [29]:
test

array([3.    , 2.    , 3.    , 4.    , 3.14  , 2.0001])

In [30]:
test.dtype

dtype('float64')

Количество байт, потребляемое элементами массива.

In [31]:
test.nbytes

48

In [32]:
np.fromfunction(lambda i, j: i + j, (3, 3), dtype = int) #элементы зависят от индекса

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

Возвращает массив, состоящий из нулей той же формы и типа, что и данный массив.

In [33]:
np.zeros_like(test)

array([0., 0., 0., 0., 0., 0.])

## Доступ к элементам массива

Создаю массивы.

In [34]:
x1 = np.random.randint(10, size=6)  
x2 = np.random.randint(10, size=(3, 4))  
x3 = np.random.randint(10, size=(3, 4, 5))  

In [35]:
x1

array([6, 3, 9, 7, 9, 1])

In [36]:
x2

array([[6, 5, 1, 8],
       [0, 3, 6, 7],
       [8, 4, 2, 5]])

In [37]:
x3

array([[[6, 3, 2, 5, 2],
        [0, 0, 1, 3, 8],
        [7, 0, 9, 4, 1],
        [7, 6, 8, 6, 3]],

       [[8, 5, 5, 5, 4],
        [0, 3, 7, 6, 5],
        [9, 8, 1, 2, 1],
        [7, 4, 4, 3, 9]],

       [[1, 4, 5, 6, 9],
        [8, 3, 6, 3, 1],
        [2, 6, 9, 2, 1],
        [8, 5, 2, 8, 4]]])

Практикую доступ к элементам.

In [38]:
x1[0]

6

In [39]:
x1[-1]

1

In [40]:
x2

array([[6, 5, 1, 8],
       [0, 3, 6, 7],
       [8, 4, 2, 5]])

In [41]:
x2[0,1]

5

In [42]:
x2[0,-1]

8

In [43]:
x1

array([6, 3, 9, 7, 9, 1])

Конец, указанный в срезе, не учитывается по шагу. Возвращается массив.

In [44]:
# x[start:stop:step]
x1[1:-1:2]

array([3, 7])

In [45]:
x1[:5]

array([6, 3, 9, 7, 9])

In [46]:
x1[::2]

array([6, 9, 9])

In [47]:
x1[::-1] # разворот

array([1, 9, 7, 9, 3, 6])

In [48]:
x2

array([[6, 5, 1, 8],
       [0, 3, 6, 7],
       [8, 4, 2, 5]])

Сначала строчки, потом столбцы через запятую.

In [49]:
x2[:2,:2]

array([[6, 5],
       [0, 3]])

In [50]:
x2[:,::-1]

array([[8, 1, 5, 6],
       [7, 6, 3, 0],
       [5, 2, 4, 8]])

Вот так можно указывать столбцы.

In [51]:
x2[:,[3,2,1]]

array([[8, 1, 5],
       [7, 6, 3],
       [5, 2, 4]])

Просто весь второй столбец.

In [52]:
x2[:,2] #столбец

array([1, 6, 2])

In [53]:
x2[2,:] #строка

array([8, 4, 2, 5])

In [54]:
x2_child = x2[2,:] # подмассив

In [55]:
x2_child[0] = 2023

А вот так работают массивы, так как обе переменные будут ссылаться на один объект в памяти, изменение одной из них будет видно и в других.

In [56]:
x2_child

array([2023,    4,    2,    5])

In [57]:
x2

array([[   6,    5,    1,    8],
       [   0,    3,    6,    7],
       [2023,    4,    2,    5]])

In [58]:
x2_grownup_child = x2[0,:].copy() # копия для разрыва связи с базовым массивом

In [59]:
x2_grownup_child

array([6, 5, 1, 8])

In [60]:
x2_grownup_child[0] = 2023

In [61]:
x2_grownup_child

array([2023,    5,    1,    8])

In [62]:
x2

array([[   6,    5,    1,    8],
       [   0,    3,    6,    7],
       [2023,    4,    2,    5]])

## Изменение структуры массива

In [63]:
grid = np.arange(1, 10)
grid

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
grid = grid.reshape(3, 3) #создаём массив потом меняем его форму
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [65]:
np.arange(1, 10).reshape(3, 2)

ValueError: cannot reshape array of size 9 into shape (3,2)

In [71]:
x = np.array([1, 2, 3])
x.reshape((1, 3)) 

array([[1, 2, 3]])

In [72]:
x.reshape(3, 1) 

array([[1],
       [2],
       [3]])

Увеличиваю размерность массива.

In [73]:
x[np.newaxis,:]

array([[1, 2, 3]])

In [74]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [75]:
z = np.array([99, 99, 99])
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [76]:
grid1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

Буду склеивать элементы массивов на первом уровне вложенности.

In [77]:
grid2 = np.zeros((2,3))
grid2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [78]:
np.concatenate([grid1, grid2]) # конкатенация по 1 - ому измерению

array([[1., 2., 3.],
       [4., 5., 6.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [79]:
np.concatenate([grid1, grid2],axis = 1) # конкатенация по 2 - ому измерению

array([[1., 2., 3., 0., 0., 0.],
       [4., 5., 6., 0., 0., 0.]])

Присоединяю данные по вертикальной и горизонтальной осям.

In [80]:
np.vstack([grid1, grid2])

array([[1., 2., 3.],
       [4., 5., 6.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [81]:
np.hstack([grid1, grid2])

array([[1., 2., 3., 0., 0., 0.],
       [4., 5., 6., 0., 0., 0.]])

In [82]:
x = np.array([1, 2, 3, 99, 99, 3, 2, 1])
np.split(x, 4) # разделение массива

[array([1, 2]), array([ 3, 99]), array([99,  3]), array([2, 1])]

Разделит массив по указанным индексам.

In [83]:
np.split(x,[3, 5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [84]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [85]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [86]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


# Задания

## 1.

### 2. Реализуйте функцию для создания "шахматной" квадратной двоичной матрицы произвольного размера.

In [87]:
def get_chess_form(n):
    chess_template_1 = np.zeros(n, dtype=int)
    chess_template_2 = np.zeros(n, dtype=int)
    chess_template_1[1::2] = 1
    chess_template_2[::2] = 1
    chess_template_3 = np.vstack([chess_template_1, chess_template_2])
    res = np.vstack([chess_template_3] * int (n / 2))
    if (n % 2):
        res = np.vstack([res, chess_template_1])
    return res

In [88]:
N = 8
chess_arr = get_chess_form(N)
chess_arr

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

### 3. Реализуйте функцию для создания матрицы для сетки координа x и y, покрывающими область [0,1] x [0,1] на плоскости. На вход функция принимает количество точек сетки.

Первый способ решения.

In [299]:
def get_grid_digits(n):
    t = np.linspace(0, 1, n)
    t_grid = np.vstack([t] * n)
    # t_grid[:,:1] = t_grid[:,:1] + np.reshape(t[::-1], (n, 1))
    return t_grid

In [300]:
get_grid_digits(6)

array([[0. , 0.2, 0.4, 0.6, 0.8, 1. ],
       [0. , 0.2, 0.4, 0.6, 0.8, 1. ],
       [0. , 0.2, 0.4, 0.6, 0.8, 1. ],
       [0. , 0.2, 0.4, 0.6, 0.8, 1. ],
       [0. , 0.2, 0.4, 0.6, 0.8, 1. ],
       [0. , 0.2, 0.4, 0.6, 0.8, 1. ]])

Второй способ решения.

In [301]:
def get_grid_lists(n):
    test = np.zeros((n, n, 2))
    t = np.linspace(0, 1, n)
    test[:, :, 1:] = np.reshape(t[::-1], (n, 1, 1))
    test[:, :, :1] = np.reshape(t, (n, 1))
    return test

In [302]:
show_arr(get_grid_lists(6))

[0. 1.] [0.2 1. ] [0.4 1. ] [0.6 1. ] [0.8 1. ] [1. 1.] 
[0.  0.8] [0.2 0.8] [0.4 0.8] [0.6 0.8] [0.8 0.8] [1.  0.8] 
[0.  0.6] [0.2 0.6] [0.4 0.6] [0.6 0.6] [0.8 0.6] [1.  0.6] 
[0.  0.4] [0.2 0.4] [0.4 0.4] [0.6 0.4] [0.8 0.4] [1.  0.4] 
[0.  0.2] [0.2 0.2] [0.4 0.2] [0.6 0.2] [0.8 0.2] [1.  0.2] 
[0. 0.] [0.2 0. ] [0.4 0. ] [0.6 0. ] [0.8 0. ] [1. 0.] 


Как я разбирался со вторым способом.

In [303]:
N = 5
test = np.zeros((N, N, 2))

In [304]:
def show_arr(arr):
    for i in arr:
        for j in range(len(i)):
            print(i[j], end=' ')
        print()

In [305]:
show_arr(test)

[0. 0.] [0. 0.] [0. 0.] [0. 0.] [0. 0.] 
[0. 0.] [0. 0.] [0. 0.] [0. 0.] [0. 0.] 
[0. 0.] [0. 0.] [0. 0.] [0. 0.] [0. 0.] 
[0. 0.] [0. 0.] [0. 0.] [0. 0.] [0. 0.] 
[0. 0.] [0. 0.] [0. 0.] [0. 0.] [0. 0.] 


In [306]:
t = np.linspace(0, 1, N)

In [307]:
t

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [308]:
test

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [309]:
show_arr(test)

[0. 0.] [0. 0.] [0. 0.] [0. 0.] [0. 0.] 
[0. 0.] [0. 0.] [0. 0.] [0. 0.] [0. 0.] 
[0. 0.] [0. 0.] [0. 0.] [0. 0.] [0. 0.] 
[0. 0.] [0. 0.] [0. 0.] [0. 0.] [0. 0.] 
[0. 0.] [0. 0.] [0. 0.] [0. 0.] [0. 0.] 


In [310]:
test[:, :, :1]

array([[[0.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.]]])

In [311]:
t

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [312]:
test[:, :, 1:] = np.reshape(t[::-1], (N, 1, 1))

In [313]:
show_arr(test)

[0. 1.] [0. 1.] [0. 1.] [0. 1.] [0. 1.] 
[0.   0.75] [0.   0.75] [0.   0.75] [0.   0.75] [0.   0.75] 
[0.  0.5] [0.  0.5] [0.  0.5] [0.  0.5] [0.  0.5] 
[0.   0.25] [0.   0.25] [0.   0.25] [0.   0.25] [0.   0.25] 
[0. 0.] [0. 0.] [0. 0.] [0. 0.] [0. 0.] 


In [314]:
test[:, :, :1] = np.reshape(t, (N, 1))

In [315]:
show_arr(test)

[0. 1.] [0.25 1.  ] [0.5 1. ] [0.75 1.  ] [1. 1.] 
[0.   0.75] [0.25 0.75] [0.5  0.75] [0.75 0.75] [1.   0.75] 
[0.  0.5] [0.25 0.5 ] [0.5 0.5] [0.75 0.5 ] [1.  0.5] 
[0.   0.25] [0.25 0.25] [0.5  0.25] [0.75 0.25] [1.   0.25] 
[0. 0.] [0.25 0.  ] [0.5 0. ] [0.75 0.  ] [1. 0.] 


In [316]:
np.reshape(t, (N, 1))

array([[0.  ],
       [0.25],
       [0.5 ],
       [0.75],
       [1.  ]])

In [317]:
test[:, :, :1]

array([[[0.  ],
        [0.25],
        [0.5 ],
        [0.75],
        [1.  ]],

       [[0.  ],
        [0.25],
        [0.5 ],
        [0.75],
        [1.  ]],

       [[0.  ],
        [0.25],
        [0.5 ],
        [0.75],
        [1.  ]],

       [[0.  ],
        [0.25],
        [0.5 ],
        [0.75],
        [1.  ]],

       [[0.  ],
        [0.25],
        [0.5 ],
        [0.75],
        [1.  ]]])